#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)

RUN_NAME="${RUN_NAME:-qwen3_30b_hspec_exp_a1}"
HSPEC_RUN_NAME="${HSPEC_RUN_NAME:-${RUN_NAME}}"
HSPEC_RUN_UID="${HSPEC_RUN_UID:-$(date -u '+%Y%m%dT%H%M%SZ')_$$}"

A1_OUTPUT_ROOT="${A1_OUTPUT_ROOT:-${PROJECT_ROOT}/output/exp_A1}"
A1_MANIFEST_DIR="${A1_MANIFEST_DIR:-${A1_OUTPUT_ROOT}/manifests}"
A1_LOG_DIR="${A1_LOG_DIR:-${A1_OUTPUT_ROOT}/logs}"
mkdir -p "${A1_OUTPUT_ROOT}" "${A1_MANIFEST_DIR}" "${A1_LOG_DIR}"

A1_TOTAL_EPOCHS="${A1_TOTAL_EPOCHS:-2}"
A1_TEST_FREQ="${A1_TEST_FREQ:--1}"
A1_DATASET_FRACTION="${A1_DATASET_FRACTION:-0.004}"
A1_HSPEC_NUM_SPECULATIVE_TOKENS="${A1_HSPEC_NUM_SPECULATIVE_TOKENS:-15}"
A1_HSPEC_SIMILARITY_THRESHOLD="${A1_HSPEC_SIMILARITY_THRESHOLD:-0.85}"

export RUN_NAME
export HSPEC_RUN_NAME
export HSPEC_RUN_UID
export HSPEC_DUMP="${HSPEC_DUMP:-0}"
export HSPEC_LEGACY_DATAPROTO_HS="${HSPEC_LEGACY_DATAPROTO_HS:-0}"
export HSPEC_STRICT_DESCRIPTOR_MODE="${HSPEC_STRICT_DESCRIPTOR_MODE:-1}"
export HSPEC_STEP0_RUNTIME_ASSERTS="${HSPEC_STEP0_RUNTIME_ASSERTS:-1}"

export HSPEC_RAW_STORE_GC_AFTER_EPOCH="${HSPEC_RAW_STORE_GC_AFTER_EPOCH:-0}"
export HSPEC_DELETE_TRAJECTORY_AFTER_BUILD="${HSPEC_DELETE_TRAJECTORY_AFTER_BUILD:-0}"
export HSPEC_RAW_STORE_MAX_BYTES="${HSPEC_RAW_STORE_MAX_BYTES:-0}"
export HSPEC_RAW_STORE_MAX_FILES="${HSPEC_RAW_STORE_MAX_FILES:-0}"
export HSPEC_RAW_STORE_MAX_BYTES_PER_EPOCH="${HSPEC_RAW_STORE_MAX_BYTES_PER_EPOCH:-0}"
export HSPEC_COLLECT_MAX_BYTES_PER_WORKER="${HSPEC_COLLECT_MAX_BYTES_PER_WORKER:-0}"
export HSPEC_RAW_STORE_BUDGET_DELETE="${HSPEC_RAW_STORE_BUDGET_DELETE:-0}"

export HSPEC_TABLE_STORE_GC_AFTER_SWAP="${HSPEC_TABLE_STORE_GC_AFTER_SWAP:-0}"
export HSPEC_TABLE_STORE_RETAIN_VERSIONS="${HSPEC_TABLE_STORE_RETAIN_VERSIONS:-64}"

export HSPEC_EPOCH_BUILD_BARRIER_TIMEOUT_S="${HSPEC_EPOCH_BUILD_BARRIER_TIMEOUT_S:-0}"
export HSPEC_SWAP_PARTIAL_ON_TIMEOUT="${HSPEC_SWAP_PARTIAL_ON_TIMEOUT:-0}"
export HSPEC_BUILD_TIMEOUT_DISCARD_UNFINISHED="${HSPEC_BUILD_TIMEOUT_DISCARD_UNFINISHED:-1}"
export HSPEC_BUILD_MAX_PENDING_EPOCHS="${HSPEC_BUILD_MAX_PENDING_EPOCHS:-0}"
export HSPEC_BUILD_QUEUE_MAX_LAG_S="${HSPEC_BUILD_QUEUE_MAX_LAG_S:-0}"

export HSPEC_DEBUG="${HSPEC_DEBUG:-0}"
export HSPEC_TRACE="${HSPEC_TRACE:-0}"
export HSPEC_PROFILE="${HSPEC_PROFILE:-0}"
export HSPEC_ALIGN_DEBUG="${HSPEC_ALIGN_DEBUG:-0}"

export HSPEC_STORE_DIR="${HSPEC_STORE_DIR:-/home/sharedata/xy_hspec/hspec_store/${RUN_NAME}/${HSPEC_RUN_UID}}"
export HSPEC_TABLE_STORE_DIR="${HSPEC_TABLE_STORE_DIR:-/home/sharedata/xy_hspec/hspec_table_store/${RUN_NAME}/${HSPEC_RUN_UID}}"
export OUT="${OUT:-${A1_LOG_DIR}/${RUN_NAME}_${HSPEC_RUN_UID}.log}"

MANIFEST_PATH="${A1_MANIFEST_DIR}/${RUN_NAME}_${HSPEC_RUN_UID}.env"
cat > "${MANIFEST_PATH}" <<EOF
RUN_NAME=${RUN_NAME}
HSPEC_RUN_NAME=${HSPEC_RUN_NAME}
HSPEC_RUN_UID=${HSPEC_RUN_UID}
HSPEC_STORE_DIR=${HSPEC_STORE_DIR}
HSPEC_TABLE_STORE_DIR=${HSPEC_TABLE_STORE_DIR}
OUT=${OUT}
HSPEC_DUMP=${HSPEC_DUMP}
HSPEC_LEGACY_DATAPROTO_HS=${HSPEC_LEGACY_DATAPROTO_HS}
HSPEC_STRICT_DESCRIPTOR_MODE=${HSPEC_STRICT_DESCRIPTOR_MODE}
HSPEC_STEP0_RUNTIME_ASSERTS=${HSPEC_STEP0_RUNTIME_ASSERTS}
HSPEC_RAW_STORE_GC_AFTER_EPOCH=${HSPEC_RAW_STORE_GC_AFTER_EPOCH}
HSPEC_DELETE_TRAJECTORY_AFTER_BUILD=${HSPEC_DELETE_TRAJECTORY_AFTER_BUILD}
HSPEC_RAW_STORE_MAX_BYTES=${HSPEC_RAW_STORE_MAX_BYTES}
HSPEC_RAW_STORE_MAX_FILES=${HSPEC_RAW_STORE_MAX_FILES}
HSPEC_RAW_STORE_MAX_BYTES_PER_EPOCH=${HSPEC_RAW_STORE_MAX_BYTES_PER_EPOCH}
HSPEC_COLLECT_MAX_BYTES_PER_WORKER=${HSPEC_COLLECT_MAX_BYTES_PER_WORKER}
HSPEC_RAW_STORE_BUDGET_DELETE=${HSPEC_RAW_STORE_BUDGET_DELETE}
HSPEC_TABLE_STORE_GC_AFTER_SWAP=${HSPEC_TABLE_STORE_GC_AFTER_SWAP}
HSPEC_TABLE_STORE_RETAIN_VERSIONS=${HSPEC_TABLE_STORE_RETAIN_VERSIONS}
HSPEC_EPOCH_BUILD_BARRIER_TIMEOUT_S=${HSPEC_EPOCH_BUILD_BARRIER_TIMEOUT_S}
HSPEC_SWAP_PARTIAL_ON_TIMEOUT=${HSPEC_SWAP_PARTIAL_ON_TIMEOUT}
HSPEC_BUILD_TIMEOUT_DISCARD_UNFINISHED=${HSPEC_BUILD_TIMEOUT_DISCARD_UNFINISHED}
HSPEC_BUILD_MAX_PENDING_EPOCHS=${HSPEC_BUILD_MAX_PENDING_EPOCHS}
HSPEC_BUILD_QUEUE_MAX_LAG_S=${HSPEC_BUILD_QUEUE_MAX_LAG_S}
A1_TOTAL_EPOCHS=${A1_TOTAL_EPOCHS}
A1_TEST_FREQ=${A1_TEST_FREQ}
A1_DATASET_FRACTION=${A1_DATASET_FRACTION}
A1_HSPEC_NUM_SPECULATIVE_TOKENS=${A1_HSPEC_NUM_SPECULATIVE_TOKENS}
A1_HSPEC_SIMILARITY_THRESHOLD=${A1_HSPEC_SIMILARITY_THRESHOLD}
EOF

echo "A1 collect manifest: ${MANIFEST_PATH}"
echo "A1 raw store dir: ${HSPEC_STORE_DIR}"
echo "A1 table store dir: ${HSPEC_TABLE_STORE_DIR}"
echo "A1 train log: ${OUT}"

bash "${SCRIPT_DIR}/train_grpo_qwen3_30b_hspec.sh" \
  trainer.total_epochs="${A1_TOTAL_EPOCHS}" \
  trainer.test_freq="${A1_TEST_FREQ}" \
  data.dataset_fraction="${A1_DATASET_FRACTION}" \
  actor_rollout_ref.rollout.hspec_num_speculative_tokens="${A1_HSPEC_NUM_SPECULATIVE_TOKENS}" \
  actor_rollout_ref.rollout.hspec_similarity_threshold="${A1_HSPEC_SIMILARITY_THRESHOLD}" \
  "$@"
